### ISSUE TITLE
How do I use this project?

### ISSUE THREAD

**Issue by abd5ge3** [acheronfail/rttw#3]
I am just wondering how i can set this up on my own environment?

**Comment by acheronfail** [comment]
Hi there!
Thanks for showing interest in this project 😄 

I've just merged master with another branch and this includes an updated README. So give that a go, and if you have any questions feel free to shout out.

**Comment by acheronfail** [comment]
I'm going to close this because I think the recent changes to the README assist in this.
If you have any more questions feel free to leave a comment.
